from pico2d import *

#게임 상태
STATE_TITLE = 0
STATE_GAMEPLAY = 1
STATE_VIEWING_ART = 2
STATE_FADING_OUT = 3
STATE_FADING_IN = 4
STATE_POST_FADE_DELAY = 5

#그림 id
ART_NONE = 0
ART_MONALISA = 1
ART_STARRY_NIGHT = 2
ART_ISLAND = 3
ART_EATING_PLANET = 4
ART_VENUS = 5

#이상 현상 id 상수
ANOMALY_MONALISA_SMILE = 1 #15개 이상현상까지 사용 예정
ANOMALY_HAND_PRINT = 2
ANOMALY_PLAYER_GIANT = 3
ANOMALY_DARK_ZONE = 4
ANOMALY_SHADOW_MAN = 5

#게임 설정 상수
FINAL_SUCCESS_COUNT = 7
INTERACTION_DISTANCE = 75
POST_FADE_DELAY_TIME = 0.3

#캔버스 설정
CANVAS_WIDTH = 800
CANVAS_HEIGHT = 600

#모나리자
MONA_X = 100
MONA_Y = 500
MONA_W = 100
MONA_H = 150

#별이 빛나는 밤
STARRY_NIGHT_Y = 500
STARRY_NIGHT_W= 100
STARRY_NIGHT_H = 150
STARRY_NIGHT_X = MONA_X + (MONA_W // 2) + (STARRY_NIGHT_W // 2) + 100

#떠있는 섬
ISLAND_Y = 500
ISLAND_W = 100
ISLAND_H = 150
ISLAND_X = STARRY_NIGHT_X + (STARRY_NIGHT_W // 2) + (ISLAND_W // 2) + 100

#행성을 먹는 자
EATING_PLANET_Y = 500
EATING_PLANET_W = 100
EATING_PLANET_H = 150
EATING_PLANET_X = ISLAND_X + (ISLAND_W // 2) + (EATING_PLANET_W // 2) + 100

#손바닥 자국
HAND_PRINT_X = 400
HAND_PRINT_Y = 300
HAND_PRINT_W = 600
HAND_PRINT_H = 600

VENUS_X = 100
VENUS_Y = 130
VENUS_W = 100
VENUS_H = 200

#확대보기
MONA_LARGE_W = int(CANVAS_WIDTH * 0.8)
MONA_LARGE_H = int(CANVAS_HEIGHT * 0.9)


